# 项目信息配置
spring:
  application:
    name: framework
  profiles:
    active: dev

# 端口配置
server:
  port: 8080
  servlet:
    context-path: /framework
    encoding:
      force: true
      enabled: true
      charset: UTF-8

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      select-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_empty
      table-underline: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
  mapper-locations: classpath*:mybatis/*Mapper.xml
  type-aliases-package: com.wangfajun.framework.model.entity

# 默认日志配置
logging:
  #日志文件路径配置
  config: classpath:logback-spring.xml
  level:
    root: ERROR
  file:
    path: /opt/logs/framework

# 数据加密KEY
aes:
  key: laowang_framework
# 读取外部配置文件
config:
  file:
    absolute:
      path: /data/zhundian-config/application-framework.yml